on: 
  push:
    branches: 
      - master 


jobs:
  build: 
    runs-on: ubunto-latest 

    steps: 

      - name: "before"
        run: ls 

      - uses: actions/checkout@v3  
      - name: "after"
      
        run: ls  

